### PR TITLE
fix(frontend): zoom visibility labels in checkbox trees

### LINKED ISSUE #195: Data hidden symbol shown when data is visible
[An example](https://jamaica.infrastructureresilience.org/exposure?lat=18.05933&lon=-77.72317&zoom=14.59&assets=true&hazards=false&buildings=false&buildingsStyle=type&regions=false&regionsStyle=boundaries&hazardsStyle=&terrestrialStyle=landuse&marineStyle=habitat&netTree=03&droughtStyle=adaptation&assetsStyle=type&terrestrial=false&marine=false) exposure view, where Power/Transmission/Poles are being displayed in the map, but are flagged as not displayed by the grey eye with a line through it. 

not_hidden_jsrat

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove `app/state/zoom`, which isn't used anywhere, and link checkbox trees to `mapViewState.zoom`, from the shared data map library.

- fixes #195.

https://github.com/user-attachments/assets/d205d474-d950-493a-a552-cfa5067b375d

### CODE REVIEW

File: frontend/src/app/sidebar/ui/LayerLabel.tsx [hunk 1]
```diff
@@ -17,6 +17,7 @@ export const LayerLabel = ({
   minZoom?: number;
   visible: boolean;
 }) => {
+  console.log('LayerLabel', label, type, color, minZoom, visible);
```
Comment (eatyourgreens) [inline frontend/src/app/sidebar/ui/LayerLabel.tsx:20]: debugging log
```suggestion
```

File: frontend/src/app/sidebar/ui/LayerLabel.tsx [hunk 2]
```diff
@@ -29,7 +30,9 @@ export const LayerLabel = ({
 };
 
 function ZoomVisibility({ minZoom }: { minZoom: number }) {
-  const currentZoom = useRecoilValue(zoomState);
+  const mapViewState = useRecoilValue(mapViewStateState);
+  const currentZoom = mapViewState.zoom;
+  console.log('ZoomVisibility', minZoom, currentZoom);
```
Comment (eatyourgreens) [inline frontend/src/app/sidebar/ui/LayerLabel.tsx:35]: debugging log
```suggestion
```
